spring:
  mail:
    allow-circular-references: true
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: haquanghung309@gmail.com
    password: vvokccqlgviqrgnt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  session:
    store-type: redis
  datasource:
    url: jdbc:postgresql://ep-weathered-rain-a1wh6rnh.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=D0pJt2hMKUYC&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql